/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BoldEditor: typeof import('./src/components/survey-comps/edit-items/bold-editor.vue')['default']
    ButtonGroup: typeof import('./src/components/survey-comps/edit-items/button-group.vue')['default']
    ColorEditor: typeof import('./src/components/survey-comps/edit-items/color-editor.vue')['default']
    DateTime: typeof import('./src/components/survey-comps/edit-items/date-time.vue')['default']
    DescEditor: typeof import('./src/components/survey-comps/edit-items/desc-editor.vue')['default']
    EditPanel: typeof import('./src/components/survey-comps/edit-items/edit-panel.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    MaterialsHeader: typeof import('./src/components/survey-comps/common/materials-header.vue')['default']
    MultiplePicSelect: typeof import('./src/components/survey-comps/materials/select-comps/multiple-pic-select.vue')['default']
    MultipleSelect: typeof import('./src/components/survey-comps/materials/select-comps/multiple-select.vue')['default']
    OptionEditor: typeof import('./src/components/survey-comps/edit-items/option-editor.vue')['default']
    OptionSelect: typeof import('./src/components/survey-comps/materials/select-comps/option-select.vue')['default']
    PageHeader: typeof import('./src/components/common/page-header/index.vue')['default']
    PicItem: typeof import('./src/components/survey-comps/common/pic-item.vue')['default']
    PicOptionsEditor: typeof import('./src/components/survey-comps/edit-items/pic-options-editor.vue')['default']
    PositionEditor: typeof import('./src/components/survey-comps/edit-items/position-editor.vue')['default']
    RateScore: typeof import('./src/components/survey-comps/materials/advanced-comps/rate-score.vue')['default']
    RateScoreEditor: typeof import('./src/components/survey-comps/edit-items/rate-score-editor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SinglePicSelect: typeof import('./src/components/survey-comps/materials/select-comps/single-pic-select.vue')['default']
    SingleSelect: typeof import('./src/components/survey-comps/materials/select-comps/single-select.vue')['default']
    SizeEditor: typeof import('./src/components/survey-comps/edit-items/size-editor.vue')['default']
    SlantEditor: typeof import('./src/components/survey-comps/edit-items/slant-editor.vue')['default']
    SurveyCompGroup: typeof import('./src/components/editor/survey-comp-group.vue')['default']
    SurveyCompItem: typeof import('./src/components/editor/survey-comp-item.vue')['default']
    TextInput: typeof import('./src/components/survey-comps/materials/input-comps/text-input.vue')['default']
    TextNode: typeof import('./src/components/survey-comps/materials/node-comps/text-node.vue')['default']
    TitleEditor: typeof import('./src/components/survey-comps/edit-items/title-editor.vue')['default']
    TypeEditor: typeof import('./src/components/survey-comps/edit-items/type-editor.vue')['default']
  }
}
