/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconCustomVue: typeof import('~icons/custom/vue')['default']
    IconMdiAccount: typeof import('~icons/mdi/account')['default']
    IconMdiAccountCircle: typeof import('~icons/mdi/account-circle')['default']
  }
}
